version: '3'

services:

  mariadb:
    image: mariadb:10.4
    ports:
      - 3307:3306
    volumes:
      - ~/apps/blog/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=blogs
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=username
